# Generated by Django 2.1.5 on 2021-12-06 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amigo_certo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
