# Generated by Django 2.1.5 on 2021-12-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amigo_certo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='necessidades',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
    ]
